# Social Vulnerability Ireland - Subet vulnerability results

## Environment

### R Libraries
The relvant R libraries are imported in to the kernal:

In [1]:
# Load R libraries
if(!require("pacman"))
    install.packages("pacman")

p_load("sf", "tidyverse")

print("Loaded Packages:")
p_loaded()

Loading required package: pacman

[1] "Loaded Packages:"

 [1] "lubridate" "forcats"   "stringr"   "dplyr"     "purrr"     "readr"
 [7] "tidyr"     "tibble"    "ggplot2"   "tidyverse" "sf"        "pacman"

### Output directory

In [2]:
# create the output directory if it does not exist
output_dir <- file.path("../..","3_outputs","Ireland","2022","Cork")
if(!dir.exists(output_dir)){
    dir.create(output_dir, recursive = TRUE)
    print(paste0(output_dir, " created"))
}

### Set the GUID

In [3]:
GUID <- "SA_GUID__1"

## Load Data

### Import the data

In [4]:
# Load Social Vulnerability Index data
svi_input <- st_read("../../3_outputs/Ireland/2022/social_vulnerability_index_ireland_2022.geojson")
head(svi_input)

# Load census output areas
census_areas <- st_read("../../0_data/boundaries/Ireland/census_small_areas/2022/SMALL_AREA_2022.shp")
head(census_areas)

Reading layer `social_vulnerability_index_ireland_2022' from data source
  `/Cities/3_outputs/Ireland/2022/social_vulnerability_index_ireland_2022.geojson'
  using driver `GeoJSON'
Simple feature collection with 18919 features and 46 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 417471.5 ymin: 519663.7 xmax: 734481.1 ymax: 966896.3
Projected CRS: IRENET95 / Irish Transverse Mercator

Registered S3 method overwritten by 'geojsonsf':
  method        from
  print.geojson geojson

  SA_GUID__1                           early_childhood age_middle_to_oldest_old
1 000581a3-4ebd-4a74-b5f8-0bd78cd7ede5  3.3880435      -0.8683184
2 00275248-3d78-4fdb-8e5c-8ff1f76aebea -1.2041476       1.0830212
3 002b83e4-5cce-414a-8570-871a50ae0964  0.2940109      -0.6563918
4 005eec3f-d746-480f-ae2c-bc6f1151548d -1.3337162       1.4547264
5 00b00ae4-229d-455d-84f1-d6face4876b1  1.7131001      -1.2060316
6 00df2b78-66c8-4009-89e0-0e14e15e4208  1.5084163      -0.8589597
  poor_health disability  one_parent_households
1 -0.72494112 -0.92235833 -0.9537932
2  0.27801178 -0.62611003 -0.5813707
3  0.07647292  0.06773408  0.3083236
4  0.49313225  0.45603900 -1.0918818
5 -0.32805634 -0.03080027  3.2416831
6 -1.03118100 -1.02730679 -0.4959203
  three_or_more_children_households low_skilled_employment farmers
1 -0.28864382                       -0.3191812             -0.5775435
2  0.24855343                       -0.7175350              0.2814244
3 -0.06192013                       -0.7370951             -0.1126775
4 -1.18351563                       -1.9157382             -0.5775435
5  1.26642096                        1.5271694             -0.5775435
6 -0.57201990                        0.4816479             -0.4599295
  unemployment geometry                       ⋯ housing_characteristics
1 -0.61650259  MULTIPOLYGON (((676048.9 72... ⋯ -0.51537733
2 -0.23523246  MULTIPOLYGON (((637187.3 72... ⋯ -0.08272206
3  0.22240140  MULTIPOLYGON (((645674.5 69... ⋯ -0.43095487
4 -0.07660151  MULTIPOLYGON (((716705.1 72... ⋯ -0.34810226
5  0.75768133  MULTIPOLYGON (((697195.3 79... ⋯ -0.57973227
6 -0.97841257  MULTIPOLYGON (((662960.4 71... ⋯ -0.50830359
  physical_environment sensitivity prepare    respond    recover
1  0.2163239            0.38290372 -0.4856123 -0.3377139 -1.3729086
2 -0.1150856           -0.20594059 -1.0185818 -0.9052009 -0.5397312
3  0.3196619           -0.09575557  1.3659655  1.7874752 -0.1097374
4  0.6397246            0.46969785  1.3940082  0.8307672 -0.3008060
5  0.4764065            0.06504954  1.1356657 -0.5626938 -0.3603958
6  0.1858483           -0.61841747 -0.5434782  0.5417954 -1.2756320
  adaptive_capacity enhanced_exposure social_vulnerability
1 -0.61316276       -0.3497016        -0.33398100
2 -1.02866162       -0.2313086        -0.93275401
3  1.32022239       -0.1301417         1.13569837
4  0.88678611        0.3410119         1.02930797
5  0.06607222       -0.1208251         0.19607516
6  0.04443066       -0.3770668        -0.09735021
  geometry
1 MULTIPOLYGON (((676048.9 72...
2 MULTIPOLYGON (((637187.3 72...
3 MULTIPOLYGON (((645674.5 69...
4 MULTIPOLYGON (((716705.1 72...
5 MULTIPOLYGON (((697195.3 79...
6 MULTIPOLYGON (((662960.4 71...

Reading layer `SMALL_AREA_2022' from data source
  `/Cities/0_data/boundaries/Ireland/census_small_areas/2022/SMALL_AREA_2022.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 18919 features and 28 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 417471.5 ymin: 519663.7 xmax: 734481.1 ymax: 966896.3
Projected CRS: IRENET95 / Irish Transverse Mercator

  OBJECTID SA_GUID_20
1 1        4c07d11e-0a4f-851d-e053-ca3ca8c0ca7f
2 2        4c07d11e-0a3a-851d-e053-ca3ca8c0ca7f
3 3        4c07d11e-0a4e-851d-e053-ca3ca8c0ca7f
4 4        4c07d11e-0a25-851d-e053-ca3ca8c0ca7f
5 5        4c07d11e-0a57-851d-e053-ca3ca8c0ca7f
6 6        4c07d11e-2df2-851d-e053-ca3ca8c0ca7f
  SA_GUID__1                           SA_PUB2011 SA_PUB2016 SA_PUB2022
1 4c07d11e-0a4f-851d-e053-ca3ca8c0ca7f 017010016  017010016  017010016
2 4c07d11e-0a3a-851d-e053-ca3ca8c0ca7f 017010046  017010046  017010046
3 4c07d11e-0a4e-851d-e053-ca3ca8c0ca7f 017010037  017010037  017010037
4 4c07d11e-0a25-851d-e053-ca3ca8c0ca7f 017010005  017010005  017010005
5 4c07d11e-0a57-851d-e053-ca3ca8c0ca7f 017010036  017010036  017010036
6 4c07d11e-2df2-851d-e053-ca3ca8c0ca7f 017010009  017010009  017010009
  SA_GEOGID_ SA_CHANGE_ SA_URBAN_A SA_URBAN_1 geometry                       ⋯
1 A017010016 0          1          Carlow     MULTIPOLYGON (((673146.5 67... ⋯
2 A017010046 4          1          Carlow     MULTIPOLYGON (((673956.3 67... ⋯
3 A017010037 0          1          Carlow     MULTIPOLYGON (((673720.6 67... ⋯
4 A017010005 0          1          Carlow     MULTIPOLYGON (((671923.3 67... ⋯
5 A017010036 0          1          Carlow     MULTIPOLYGON (((673711.8 67... ⋯
6 A017010009 4          1          Carlow     MULTIPOLYGON (((673488.5 67... ⋯
  ED_GAEILGE          ED_ID_STR ED_PART_CO COUNTY_COD COUNTY_ENG COUNTY_GAE
1 CEATHARLACH (TUATH) 017010    1          01         CARLOW     Ceatharlach
2 CEATHARLACH (TUATH) 017010    1          01         CARLOW     Ceatharlach
3 CEATHARLACH (TUATH) 017010    1          01         CARLOW     Ceatharlach
4 CEATHARLACH (TUATH) 017010    1          01         CARLOW     Ceatharlach
5 CEATHARLACH (TUATH) 017010    1          01         CARLOW     Ceatharlach
6 CEATHARLACH (TUATH) 017010    1          01         CARLOW     Ceatharlach
  CSO_LEA SHAPE_Leng SHAPE_Area geometry
1 CARLOW  2123.346   204944.2   MULTIPOLYGON (((673146.5 67...
2 CARLOW  2891.271   288225.4   MULTIPOLYGON (((673956.3 67...
3 CARLOW  2436.986   208426.9   MULTIPOLYGON (((673720.6 67...
4 CARLOW  2887.091   348798.6   MULTIPOLYGON (((671923.3 67...
5 CARLOW  2844.410   429349.1   MULTIPOLYGON (((673711.8 67...
6 CARLOW  1058.290    59299.2   MULTIPOLYGON (((673488.5 67...

## Filter Data

In [5]:
# Merge  the Social Vulnerability Index data and the census areas
merged_data <- merge(st_drop_geometry(svi_input), st_drop_geometry(census_areas), by = GUID)

# Filter Cork data (Cork city and suburbs code is "17", the rest of county Cork code is "18")
merged_data_cork <- merged_data %>% filter(COUNTY_COD == "17" | COUNTY_COD == "18")
merged_data_cork_ids <- merged_data_cork[,GUID]

svi_output_cork <- svi_input %>% filter(!!as.symbol(GUID) %in% merged_data_cork_ids)
nrow(svi_output_cork)
head(svi_output_cork)

[1] 2206

  SA_GUID__1                           early_childhood age_middle_to_oldest_old
1 04fa3a14-afbe-4e99-a760-f209f50d156e -0.1751081       0.90022941
2 056f5166-a6a5-45aa-99c2-bd4e5ecab938  0.8945241       0.09879282
3 06192d69-db1b-49af-b03e-8067305ba789  0.6718825      -0.20471071
4 0642d55d-8404-4fcf-8fc0-5e7ce85e11d8  4.2077987      -1.21257418
5 08ce1729-2944-4bf4-86f1-0b8c5545ed17  2.6750215      -1.22113669
6 0ad9190d-7e7c-4402-b99c-1366ce4f8a4a -1.0122613      -0.51202199
  poor_health disability one_parent_households
1 -0.6374113   1.0354936 -0.4338410
2 -0.1675958  -0.5858810 -0.3856101
3 -0.5854947   0.4152686  0.7336784
4 -1.2695713  -1.5866988 -1.2516686
5 -0.4686445  -1.5073698  0.4458323
6 -0.2827849   0.0466368 -0.3198408
  three_or_more_children_households low_skilled_employment farmers
1 -1.0229980                        -1.0620197              0.8259487
2 -0.4588344                         0.2712924             -0.5775435
3 -0.7301653                         0.6393685             -0.3244177
4 -0.6761514                        -0.8403841             -0.5775435
5  0.6247320                         0.7741581             -0.2219075
6 -0.3913507                         0.2796594             -0.4558315
  unemployment geometry                       ⋯ housing_characteristics
1  1.7070003   MULTIPOLYGON (((498746.1 53... ⋯  1.17139451
2  0.3593869   MULTIPOLYGON (((545906.9 57... ⋯  0.28067781
3 -0.3158771   MULTIPOLYGON (((570586.2 61... ⋯ -0.03881498
4 -2.1269721   MULTIPOLYGON (((566496.6 56... ⋯  0.17186172
5 -0.4970439   MULTIPOLYGON (((548155.2 55... ⋯ -0.45394071
6 -0.3996752   MULTIPOLYGON (((579895.7 59... ⋯ -0.26046751
  physical_environment sensitivity prepare     respond     recover
1 -1.90814855           0.49296903  0.06113257 -0.05771688  1.23755431
2  0.09097864           0.10526478 -0.56876794 -0.80338394 -0.20154873
3  0.14975495           0.13032809  0.66595662  0.34384632  0.09718817
4 -0.24804621           0.06098647 -1.77335609 -2.15052250 -1.48747349
5  0.15504147          -0.22916032  0.67104277 -0.92585359 -0.91960294
6 -0.25889901          -0.77264543 -0.48273512 -0.22006800 -0.35431027
  adaptive_capacity enhanced_exposure social_vulnerability
1  0.2211145        -0.86153177       -0.1661047
2 -0.5886800         0.43460072       -0.4278078
3  0.4813834         0.12972893        0.4712041
4 -1.8580879        -0.08908721       -1.5680132
5 -0.6444084        -0.34952125       -0.5551767
6 -0.4280592        -0.60732719       -0.6443571
  geometry
1 MULTIPOLYGON (((498746.1 53...
2 MULTIPOLYGON (((545906.9 57...
3 MULTIPOLYGON (((570586.2 61...
4 MULTIPOLYGON (((566496.6 56...
5 MULTIPOLYGON (((548155.2 55...
6 MULTIPOLYGON (((579895.7 59...

# Export

In [6]:
# CSV
write.csv(st_drop_geometry(svi_output_cork), file.path(output_dir, "social_vulnerability_index_cork_2022.csv"), row.names = FALSE)

# GeoJSON
st_write(svi_output_cork, file.path(output_dir, "social_vulnerability_index_cork_2022.geojson"), delete_dsn=TRUE)

# Shapefile
st_write(svi_output_cork, file.path(output_dir, "social_vulnerability_index_cork_2022.shp"), append = FALSE)

Deleting source `../../3_outputs/Ireland/2022/Cork/social_vulnerability_index_cork_2022.geojson' using driver `GeoJSON'
Writing layer `social_vulnerability_index_cork_2022' to data source
  `../../3_outputs/Ireland/2022/Cork/social_vulnerability_index_cork_2022.geojson' using driver `GeoJSON'
Writing 2206 features with 46 fields and geometry type Multi Polygon.

Warning message in abbreviate_shapefile_names(obj):
“Field names abbreviated for ESRI Shapefile driver”

Deleting layer `social_vulnerability_index_cork_2022' using driver `ESRI Shapefile'
Writing layer `social_vulnerability_index_cork_2022' to data source
  `../../3_outputs/Ireland/2022/Cork/social_vulnerability_index_cork_2022.shp' using driver `ESRI Shapefile'
Writing 2206 features with 46 fields and geometry type Multi Polygon.

**END**